### ISSUE TITLE
CWE134_Uncontrolled_Format_String

### ISSUE THREAD

**Issue by ch4rli3kop** [ssl3rd-svd/binja-snippets#8]
format string bug
- TODO
- [x] 탐지 코드 작성
- [ ] utils 모듈을 통한 탐지 성능 테스트
- [ ] 성능 테스트 후 코드 업데이트

**Comment by leehahoon** [comment]
- [ ] t1
- [ ] t2
- [ ] t3
- [ ] t4
- [ ] t5

**Comment by leehahoon** [comment]
기본적인 탐지 코드 작성
```python
def get_func_refs(func_name):
	symbol = bv.symbols[func_name]
	if len(symbol) > 1:
		for sym_type in symbol:
			if sym_type.type == SymbolType.ImportedFunctionSymbol:
				symbol = sym_type
				break
	refs = []
	for ref in bv.get_code_refs(symbol.address):
		refs.append((ref.function, ref.address))
	return refs

def solution() -> list[Function]:
	dangerous_call = []
	printf_refs = get_func_refs('printf')
	for function, addr in printf_refs:
		call_instr = function.get_low_level_il_at(addr).mlil
		#1. printf's param len == 1 and params is variable
		if len(call_instr.params) == 1 and \
			call_instr.params[0].operation == MediumLevelILOperation.MLIL_VAR:
			dangerous_call.append((function, addr))
	print(dangerous_call)
	return dangerous_call
```

윈도우 환경에서 utils 모듈 에러 발생하여 테스트 불가

**Comment by leehahoon** [comment]
일단 fsb로 탐지하는 함수명을 출력해서 임의 테스트
```python
import os
import sys

sys.path.append(os.path.dirname(os.getcwd()))

from binaryninja import *
from binaryninja.binaryview import BinaryViewType
from binaryninja.function import Function
from utils.runner import Runner
from utils.utils import get_all_files_from_path, get_matched_files_from_path


def get_func_refs(bv, func_name):
	symbol = bv.symbols[func_name]
	if len(symbol) > 1:
		for sym_type in symbol:
			if sym_type.type == SymbolType.ImportedFunctionSymbol:
				symbol = sym_type
				break
	refs = []
	for ref in bv.get_code_refs(symbol.address):
		refs.append((ref.function, ref.address))
	return refs

def solution(bv: BinaryViewType):
	dangerous_call = []
	# dangerous call
	# - printf
	# - fprintf
	# - vprintf, vfprintf, vsnprintf
	# - sprintf, snprintf
	printf_refs = get_func_refs(bv, 'printf')
	for function, addr in printf_refs:
		call_instr = function.get_low_level_il_at(addr).mlil
		#1. printf's param len == 1 and params is variable
		if len(call_instr.params) == 1 and \
			call_instr.params[0].operation == MediumLevelILOperation.MLIL_VAR:
			dangerous_call.append(function)
			print(function.name)
	#print(dangerous_call)
	return dangerous_call

if __name__ == '__main__':
	enterprise.connect()
	enterprise.authenticate_with_credentials("usrerid", "userpw")
	with enterprise.LicenseCheckout():
		file_list = get_all_files_from_path(f'D:\\binja-snippets\\CWE134_Uncontrolled_Format_String\\s01\\only_printf')
		#runner = Runner(solution, file_list)
		#runner.run(cpp_only=True)
		for file_ in file_list:
			with open_view(file_) as bv:
				print('[+]', os.path.basename(file_))
				solution(bv)
				print('')
```
![image](https://user-images.githubusercontent.com/15906121/199766216-0d439ab4-7f25-4e59-85f2-280cf45d559c.png)

실행결과, 잘 맞추는데 false positive도 같이 나옴
- 대부분 good source to bad sink에서 false positive
- 이는 taint analysis로 해당 source가 user input인지 파악하면 오탐율 줄일 수 있음
- 추후, fprintf, sprintf 등에 대한 파라미터 검사도 추가할 예정

**Comment by ch4rli3kop** [comment]
파일을 pathlib 라이브러리로 관리하는데 윈도우 환경을 고려하지 않았네요. 추가하겠습니다~

**Comment by leehahoon** [comment]
기존 작성한 taint analysis 코드에 해당 케이스에 적용 가능할 듯
- 해당 function call이 fsb로 의심된다면 get_ssa_var_definition로 None 나올 때까지 arg 역추적
- (internal하게 구현 예정)
- 만약, 중간에 문자열을 할당하는 경우 발생 시 good source로 판단

**Comment by leehahoon** [comment]
printf 함수의 인자가 fgets, read 등의 함수의 인자값으로 사용되는 경우만 FSB로 탐지
- 정확한 테스트 결과는 아니겠지만 대충 40/146 정도의 정답율 보임
- 일단 예외처리 제대로 안해준것도 있고, 여러 케이스에 대해 생각 안해봐서 이런 결과 나온 듯 (예를 들어, 아직 interprocedural하게 작성 X)
- 이전처럼 Taint Analysis없이 print(vars)인 경우만 탐지하면 "버그가 아닌 함수도 버그라고 탐지"
- 지금같은 경우, "버그인 함수를 버그가 아니라고 탐지"
- 어떻게 탐지할지 의논해봐야할 듯
<img width="664" alt="image" src="https://user-images.githubusercontent.com/15906121/200296869-8c52bb2d-1f64-4cc5-bba6-85d675fb7717.png">

**Comment by leehahoon** [comment]
Interprocedural하게 Taint analysis해서 FSB 탐지 진행중
아래와 같이 안되는 케이스 발생해서 추후 예외추가 예정
- return printf(format: *(arg1 + 0x10)) --> socket_66.out
- printf(format: badSource(&var_78)) --> socket_42.out

**Comment by leehahoon** [comment]
위의 케이스 예외추가 후 결과
```
c : 78  cpp : 21
result [File]:
detect: 71/78 (good: 71|false positive: 0)      missed: 5/78
```

안되는 케이스
- CWE134_Uncontrolled_Format_String__char_console_printf_68
```
000015a2      CWE134_Uncontrolled_Form...tring__char_console_printf_68_badData = var_88
000015ae      CWE134_Uncontrolled_Form...ring__char_console_printf_68b_badSink()
...
000013e9  int64_t CWE134_Uncontrolled_Format_String__char_console_printf_68b_badSink()
00001413      return printf(format: CWE134_Uncontrolled_Form...tring__char_console_printf_68_badData)
```
- CWE134_Uncontrolled_Form...tring__char_console_printf_68_badData 변수에 user input 저장 후, badSink에서 printf 인자로 넘김
- 지역변수에 대해선 inner, interprocedure 하게 taint하게 구현했지만, 전역변수에 대한 방법도 생각해야함
- ~~아 산넘어 산이네~~

**Comment by leehahoon** [comment]
현재 소스코드(22.11.21 format string detection code)
```python
import os
import sys

sys.path.append(os.path.dirname(os.getcwd()))

from binaryninja import *
from binaryninja.binaryview import BinaryViewType
from binaryninja.function import Function
from utils.runner import Runner
from utils.utils import get_all_files_from_path, get_matched_files_from_path

dangerous_flag = False
correct = 0
wrong = 0
def get_func_refs(bv, func_name):
    symbol = bv.symbols[func_name]
    if len(symbol) > 1:
        for sym_type in symbol:
            if sym_type.type == SymbolType.ImportedFunctionSymbol:
                symbol = sym_type
                break
    refs = []
    for ref in bv.get_code_refs(symbol.address):
        refs.append((ref.function, ref.address))
    return refs

def forward_taint(bv, use_ref):
    #위험하면 True, 안위험하면 False
    trace_list = use_ref
    print('lets foward taint [[+]]', trace_list)
    visited = []
    dangerous_call = ['fgets', 'gets', 'scanf', 'read', 'recv', 'connect']

    while len(trace_list) > 0:
        trace_var = trace_list.pop()
        #print('[[+]] trace_Var = ', trace_var, trace_var.operation)
        if trace_var in visited:
            return
        if trace_var.operation == MediumLevelILOperation.MLIL_SET_VAR or \
            trace_var.operation == MediumLevelILOperation.MLIL_SET_VAR_SSA or \
            trace_var.operation == MediumLevelILOperation.MLIL_SET_VAR_ALIASED:
            var = trace_var.ssa_form.dest
            #src에 대해서도 taint 필요
            print(trace_var.src.operation)
            src_var = trace_var.src
            use_ref = trace_var.ssa_form.function.get_ssa_var_uses(var)
            print('[[+]] use_ref = ', use_ref)
            for refs in use_ref:
                trace_list.append(refs)
            visited.append(trace_var)
        elif trace_var.operation == MediumLevelILOperation.MLIL_CALL_SSA:
            func_name = bv.get_function_at(trace_var.dest.constant).name
            print('[[-]] func_name = ', func_name)
            if func_name in dangerous_call:
                return True
        elif trace_var.operation == MediumLevelILOperation.MLIL_STORE_SSA:
            if trace_var.src.operation == MediumLevelILOperation.MLIL_CONST:
                #print('[+] ', trace_var.src)
                #return False
                test = 1
    return False
            

def taint_param(bv, taint_func, param_idx):
    #print('In_Taint_parma')
    print(taint_func)
    if taint_func == None:
        return None
    var = taint_func.ssa_form.params[param_idx].src
    def_ref = taint_func.function.get_ssa_var_definition(var)
    return def_ref

def get_var_from_expr(var):
    if var.left.operation == MediumLevelILOperation.MLIL_VAR or \
        var.left.operation == MediumLevelILOperation.MLIL_VAR_SSA:
        var = var.left
    else:
        var = var.right
    return var

def taint_var(bv, taint_func, param_idx):
    #위험하면 True, 안위험하면 False
    global dangerous_flag
    def_ref = taint_param(bv, taint_func, param_idx)
    taint_list = [def_ref]
    visited = []

    while len(taint_list) > 0:
        load_flag = False
       # print('[+] taint list = ',taint_list)
        trace_var = taint_list.pop()
        if trace_var == None:
            return False
        print('[+] start taint,', trace_var, trace_var.operation)
        if trace_var in visited:
            return
        if trace_var.operation == MediumLevelILOperation.MLIL_SET_VAR or \
            trace_var.operation == MediumLevelILOperation.MLIL_SET_VAR_SSA or \
            trace_var.operation == MediumLevelILOperation.MLIL_SET_VAR_ALIASED:
            if trace_var.src.operation == MediumLevelILOperation.MLIL_LOAD_SSA:
                trace_var = trace_var.src
                print('[LOAD!]', trace_var) 
                load_flag=True
            if trace_var.src.operation == MediumLevelILOperation.MLIL_VAR or \
                trace_var.src.operation == MediumLevelILOperation.MLIL_VAR_SSA or \
                load_flag:
                #taint analysis
                var = trace_var.src.ssa_form
                while type(var) != binaryninja.mediumlevelil.SSAVariable:
                    print(var, var.operation, type(var))
                    if var.operation == MediumLevelILOperation.MLIL_ADD or \
                        var.operation == MediumLevelILOperation.MLIL_SUB or \
                        var.operation == MediumLevelILOperation.MLIL_MUL or \
                        var.operation == MediumLevelILOperation.MLIL_DIVS:
                        var = get_var_from_expr(var)
                        print('+++', var)

                    elif var.operation == MediumLevelILOperation.MLIL_CONST_PTR or \
                        var.operation == MediumLevelILOperation.MLIL_CONST:
                        return
                        break
                    var = var.src
               # print(var)
                if 'arg' in var.name:
                    arg_num = var.name.split('arg')[1].split('#')[0]
                  #  print('let\'s taint~', arg_num)
                    func_refs = bv.get_code_refs(trace_var.function.source_function.start)
                    internal_refs = []
                    for ref in func_refs:
                        internal_refs.append((ref.function, ref.address))
                       # print(ref.function)
                    for func, addr in internal_refs:
                        call_instr = func.get_low_level_il_at(addr).mlil
                       # print(call_instr)
                        taint_var(bv, call_instr, int(arg_num)-1)
                def_ref = trace_var.ssa_form.function.get_ssa_var_definition(var)
               # print('[-] def_ref = ', def_ref)
                taint_list.append(def_ref)
            elif trace_var.src.operation == MediumLevelILOperation.MLIL_ADDRESS_OF:
                var = trace_var.ssa_form.dest
                src_var = trace_var.src
                #src taint 추가
                while type(src_var) != binaryninja.variable.Variable:
                    src_var = src_var.src
                src_var_name = src_var.name
                src_ref = src_var.function.get_mlil_var_refs(src_var)
                #print("!! ADDRESS OF!", trace_var, var, src_var)
                #print('!! src_ref = ', src_ref)
                for s_r in src_ref:
                    src_instr = s_r.func.get_low_level_il_at(s_r.address).mlil.ssa_form
                #    print('src taint!! = ', src_instr, src_instr.src.operation)
                    #if src_instr.src == MediumLevelILOperation.MLIL_CONST or \
						#src_instr.src == MediumLevelILOperation.MLIL_CONST_PTR:
                    if src_instr.src.operation == MediumLevelILOperation.MLIL_VAR_SSA or \
                        src_instr.src.operation == MediumLevelILOperation.MLIL_VAR or \
                        src_instr.src.operation == MediumLevelILOperation.MLIL_VAR_ALIASED or \
                        src_instr.src.operation == MediumLevelILOperation.MLIL_ADDRESS_OF:
                        var_src = src_instr.src.src
                #        print('req', var_src)
                        if var_src.name == src_var_name:
                            lets_forward_taint = [src_instr]
                           # print('qwer', lets_forward_taint)
                            if forward_taint(bv, lets_forward_taint):
                                print('!! dangerous!!')
                                dangerous_flag = True
                                return True
                #print('error?', var)
                
                use_ref = trace_var.ssa_form.function.get_ssa_var_uses(var)
                #print('[+] use_ref= ', use_ref, type(use_ref[0]))
                if forward_taint(bv, use_ref):
                    print('!! dangerous!!')
                    dangerous_flag = True
                    return True
            elif trace_var.operation == MediumLevelILOperation.MLIL_CONST:
                print("wtf?")
                return False
            
        elif trace_var.operation == MediumLevelILOperation.MLIL_CALL_SSA:
            print('THis is CALL!!!')
            call_addr = trace_var.dest.operands[0]
            call_func = bv.get_function_at(call_addr)
            param_list = call_func.parameter_vars
            call_taint_list = []
            for param_var in param_list:
                for ref in call_func.get_mlil_var_refs(param_var):
                    call_taint_list.append(call_func.get_low_level_il_at(ref.address).mlil.ssa_form)

            print(call_taint_list)
            if forward_taint(bv, call_taint_list):
                print("!!! dandan!!!")
                dangerous_flag = True
                return True
            
        
        visited.append(trace_var)
    #print("real return")
    return False

def solution(bv: BinaryViewType) -> list[Function]:
    dangerous_call = []
    global correct
    global wrong
    global dangerous_flag
    # dangerous call
    # - printf
    # - fprintf
    # - vprintf, vfprintf, vsnprintf
    # - sprintf, snprintf
    printf_refs = get_func_refs(bv, 'printf')
    #print('analysis start~', printf_refs, len(printf_refs))
    for function, addr in printf_refs:
        print('[!!!!] printf_ref checks', function.name)
        call_instr = function.get_low_level_il_at(addr).mlil
        #print(call_instr)
        dangerous_flag = False
        #1. printf's param len == 1 and params is variable
        if len(call_instr.params) == 1 and \
            call_instr.params[0].operation == MediumLevelILOperation.MLIL_VAR:
            taint_var(bv, call_instr, 0)
            if dangerous_flag:
                dangerous_call.append(function)
                print('Danger Danger!', function.name)
                correct+=1
                taint_param(bv, call_instr, 0)
            else:
                print('wrong~')
                wrong+=1
    print(dangerous_call)
    return dangerous_call

if __name__ == '__main__':
    enterprise.connect()
    enterprise.authenticate_with_credentials("", "")
    with enterprise.LicenseCheckout():
        #file_list = get_all_files_from_path(f'/Users/jaehoon/Desktop/C/testcases/CWE134_Uncontrolled_Format_String/s01/only_printf')
        #file_list = [f'/Users/jaehoon/Desktop/C/testcases/CWE134_Uncontrolled_Format_String/s01/only_printf/CWE134_Uncontrolled_Format_String__char_connect_socket_printf_66.out']
        file_list = get_all_files_from_path(f'D:\\binja-snippets\\CWE134_Uncontrolled_Format_String\\s01\\only_printf')
        #file_list = get_all_files_from_path(f'D:\\binja-snippets\\CWE134_Uncontrolled_Format_String\\s01\\only_printf\\test_file')
        #file_list = [f'D:\\binja-snippets\\CWE134_Uncontrolled_Format_String\\s01\\only_printf']
		#runner = Runner(solution, file_list)
        #runner.run(cpp_only=True)
        '''for file_ in file_list:
            with open_view(file_) as bv:
                print('[+]', os.path.basename(file_))
                solution(bv)
                print('------------------------------')
        #print(f'Score = {correct}/{correct+wrong}')
        print('this i stest')
		'''
        runner = Runner(solution, file_list)
        runner.run()

# TODO 사항
# 안되는 케이스
# - 전역변수 처리
```

**Comment by leehahoon** [comment]
전역변수 처리 완료
- 다양한 케이스에 대해 진행한 것이 아니기에 신뢰성은 낮음
```python
elif var.operation == MediumLevelILOperation.MLIL_CONST_PTR or \
                        var.operation == MediumLevelILOperation.MLIL_CONST:
                        glovar = bv.get_data_var_at(var.constant)
                        for glovar_ref in glovar.code_refs:
                            if glovar_ref.mlil.src.operation == MediumLevelILOperation.MLIL_VAR:
                                print('[+]', glovar_ref.mlil)
                                taint_list.append(glovar_ref.mlil)
                        global_var_flag = True
                        break
                    var = var.src
               # print(var)
                if global_var_flag:
                    continue 
```
- code_refs를 이용해서 taint 진행
- 단순히 STORE인 경우에도 추가적으로 taint를 하게 짠거라 잘되는지 모르겠네요.

실행결과
```
c : 77  cpp : 20
result [File]:
detect: 75/77 (good: 75|false positive: 0)      missed: 1/77
```

안되는 케이스
- CWE134_Uncontrolled_Format_String__char_console_printf_66.out
```c
void CWE134_Uncontrolled_Format_String__char_console_printf_66_bad()
{
    char * data;
    char * dataArray[5];
    char dataBuffer[100] = "";
    data = dataBuffer;
    {
        /* Read input from the console */
        size_t dataLen = strlen(data);
        /* if there is room in data, read into it from the console */
        if (100-dataLen > 1)
        {
            /* POTENTIAL FLAW: Read data from the console */
            if (fgets(data+dataLen, (int)(100-dataLen), stdin) != NULL)
            {
                /* The next few lines remove the carriage return from the string that is
                 * inserted by fgets() */
                dataLen = strlen(data);
                if (dataLen > 0 && data[dataLen-1] == '\n')
                {
                    data[dataLen-1] = '\0';
                }
            }
            else
            {
                printLine("fgets() failed");
                /* Restore NUL terminator if fgets fails */
                data[dataLen] = '\0';
            }
        }
    }
    /* put data in array */
    dataArray[2] = data;
    CWE134_Uncontrolled_Format_String__char_console_printf_66b_badSink(dataArray);
}
```
- 포인터 연산을 통해 인자 넘기고 하면 탐지 못함
![image](https://user-images.githubusercontent.com/15906121/203364019-03cf280c-a933-40ca-bb25-220663fd80ae.png)
- 바닌에서도 제대로 convert를 못하는 듯 --> 추가적인 Pointer Analaysis 필요?

**Comment by leehahoon** [comment]
- 임시방편으로 runner.py, binaryHelper.py 수정
    - 탐지코드의 answer = badVaSinkB
    - runner의 answer = CWE134_Uncontrolled_Format_String__char_connect_socket_vfprintf_17_bad
    - 그래서 우선, 다음과 같이 임시방편으로 수정했습니당.
```
#binaryHelper.py
        # some binary has just "badSink" function
        if len(bad_functions) < 1:
            bad_functions = [func for func in self.bv.functions if re.match('badSink', func.name)]

        if len(bad_functions) < 1:
            bad_functions = [func for func in self.bv.functions if re.match('_?CWE.*bad$', func.name)]
        
        bad_functions+=[func for func in self.bv.functions if re.match('badVaSink', func.name)]
        print("bad_function=",bad_functions)
...
#runner.py
if result == answer or\
            all(item in answer for item in result): #add if result include answer's element
            print(f'                                                                       good!')
```
- 현재결과
```
c : 535 cpp : 140
result [File]:
detect: 372/535 (good: 372|false positive: 0)   missed: 8/535
```
~~missed는 8개인데... 남은 155개는...? ㅋㅋㅋㅋ~~
